Repository mjmjmj9840/Cheating-Stamp, pull requests merged in 2021-11, with the labels that each got.

#120 mobileGuide 안내사항작성
  src/main/resources/application.properties
  src/main/resources/static/assets/css/mobileGuide.css
  src/main/resources/static/mobileGuide-demo.html
  src/main/resources/static/mobileGuide.html
Labels: fix

#121 모바일 응시 영상 시청 및 삭제 변경
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/model/Video.java
  src/main/java/com/example/CheatingStamp/repository/VideoRepository.java
  src/main/java/com/example/CheatingStamp/service/ExamUserService.java
  src/main/java/com/example/CheatingStamp/service/UserService.java
  src/main/java/com/example/CheatingStamp/service/VideoService.java
  src/main/resources/static/assets/js/watchingList.js
  src/main/resources/static/watchingVideo.html
Labels: feature, fix

#123 calibration.png edit
  src/main/resources/static/assets/webgazer/media/example/calibration.png
  src/main/resources/static/assets/webgazer/media/example/calibration_ex.png
Labels: fix

#124 Feature/107 mobile recording
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/dto/MobileTimestampRequestDto.java
  src/main/java/com/example/CheatingStamp/dto/VideoRequestDto.java
  src/main/java/com/example/CheatingStamp/model/Answer.java
  src/main/java/com/example/CheatingStamp/model/Video.java
  src/main/java/com/example/CheatingStamp/security/WebSecurityConfig.java
  src/main/java/com/example/CheatingStamp/service/AnswerService.java
  src/main/java/com/example/CheatingStamp/service/ExamUserService.java
  src/main/resources/static/assets/css/mHome.css
  src/main/resources/static/assets/diff-cam-scratchpad/site.js
  src/main/resources/static/fragments/header.html
  src/main/resources/static/mHome.html
Labels: feature

#125 모바일 타임스탬프 가져오기
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/service/AnswerService.java
Labels: feature, fix

#128 Feature/126 edit host domain
  src/main/java/com/example/CheatingStamp/WebConfig.java
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
Labels: feature

#129 127_Fix/add https url
  src/main/java/com/example/CheatingStamp/ConnectorConfig.java
  src/main/resources/static/assets/diff-cam-scratchpad/site.js
  src/main/resources/static/assets/js/exam.js
  src/main/resources/static/assets/js/mobileGuide.js
  src/main/resources/static/assets/webgazer/js/calibration.js
Labels: fix

#132 detailExam 뒤로가기버튼 생성
  src/main/resources/application.properties
  src/main/resources/static/assets/css/detail.css
  src/main/resources/static/calibration.html
  src/main/resources/static/detailExam.html
Labels: fix

#134 에러 수정
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/service/AnswerService.java
  src/main/java/com/example/CheatingStamp/service/ExamService.java
  src/main/java/com/example/CheatingStamp/service/UserService.java
  src/main/resources/static/assets/js/createExam.js
  src/main/resources/static/assets/js/detail.js
  src/main/resources/static/assets/js/errorMsg.js
  src/main/resources/static/errorMsg.html
  src/main/resources/static/watchingList.html
Labels: bug, fix

#136 점 모두 보이도록 pt 1 위치 수정
  src/main/resources/static/assets/css/style.css
Labels: fix

#140 calibration.png edit
  src/main/resources/static/assets/webgazer/media/example/calibration.png
Labels: fix

#142 Fix/141 mobile video error
  src/main/resources/static/assets/diff-cam-scratchpad/site.js
  src/main/resources/static/mHome.html
Labels: fix
