Repository mjmjmj9840/Cheating-Stamp, pull requests merged in 2021-09, with the labels that each got.

#44 감독관/응시자 추가 및 삭제 기능 구현
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/dto/ExamUserRequestDto.java
  src/main/java/com/example/CheatingStamp/model/ExamUser.java
  src/main/java/com/example/CheatingStamp/service/ExamUserService.java
  src/main/resources/static/assets/js/detail.js
  src/main/resources/static/detailExam.html
Labels: feature

#46 Feature/43 setting exam
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/model/Exam.java
  src/main/java/com/example/CheatingStamp/repository/ExamRepository.java
  src/main/java/com/example/CheatingStamp/repository/ExamUserRepository.java
  src/main/java/com/example/CheatingStamp/service/ExamService.java
  src/main/java/com/example/CheatingStamp/service/ExamUserService.java
  src/main/resources/static/assets/js/settingExam.js
  src/main/resources/static/examSetting.html
  src/main/resources/static/settingExam.html
Labels: feature

#49 Feature/47 exam
  src/main/resources/static/assets/js/exam.js
Labels: bug

#51 시험문제 연결&출력
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/resources/static/assets/css/exam.css
  src/main/resources/static/assets/js/exam.js
  src/main/resources/static/exam.html
Labels: feature

#52 시험영상확인화면 생성
  src/main/resources/static/assets/css/watchingVideo.css
  src/main/resources/static/assets/js/watchingVideo.js
  src/main/resources/static/watchingVideo.html
Labels: feature

#56 Fix/55 waiting
  src/main/java/com/example/CheatingStamp/service/UserService.java
  src/main/resources/static/assets/js/waiting.js
  src/main/resources/static/waiting.html
Labels: fix

#66 Feature/57 watching video
  .vscode/settings.json
  src/main/resources/static/assets/css/watchingVideo.css
  src/main/resources/static/assets/js/watchingVideo.js
  src/main/resources/static/watchingVideo-demo.html
  src/main/resources/static/watchingVideo.html
Labels: feature

#70 Feature/62 watching video
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/dto/SaveAnswerRequestDto.java
  src/main/java/com/example/CheatingStamp/model/Answer.java
  src/main/java/com/example/CheatingStamp/repository/AnswerRepository.java
  src/main/java/com/example/CheatingStamp/service/AnswerService.java
  src/main/java/com/example/CheatingStamp/service/VideoService.java
  src/main/resources/static/assets/js/exam.js
  src/main/resources/static/exam.html
Labels: feature, fix

#72 detailExam 수정
  src/main/resources/static/assets/css/detail.css
  src/main/resources/static/assets/css/settingExam.css
  src/main/resources/static/detailExam.html
  src/main/resources/static/settingExam.html
Labels: fix

#79 Calibration Rate 오류 해결
  src/main/java/com/example/CheatingStamp/service/UserService.java
  src/main/resources/static/assets/webgazer/js/calibration.js
Labels: fix

#83 Answer와 Video에 Exam에 대한 cascade 추가
  src/main/java/com/example/CheatingStamp/model/Exam.java
  src/main/java/com/example/CheatingStamp/model/Video.java
  src/main/java/com/example/CheatingStamp/repository/AnswerRepository.java
  src/main/java/com/example/CheatingStamp/service/ExamService.java
Labels: fix

#84 감독관용 페이지에서 사용자 권한 검사
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/validator/UserValidator.java
  src/main/resources/static/assets/js/errorMsg.js
  src/main/resources/static/errorMsg.html
  src/main/resources/static/index.html
Labels: feature, fix

#86 시험 상세 페이지 유효성 검사
  src/main/java/com/example/CheatingStamp/controller/ExamController.java
  src/main/java/com/example/CheatingStamp/service/ExamUserService.java
Labels: fix
